### ISSUE TITLE
The issue with pretty json

### ISSUE THREAD

**Issue by guanguans** [adhocore/php-json-fixer#12]
## Hope the fix for pretty json is still a pretty json.

**pretty json**

```json
{
    "b": [
        1,
        [
            {
                "b": 1,
                "c"
```

**fixed pretty json**

```json
{
    "b": [
        1,
        [
            {
                "b": 1,
                "c":null}]]}
```

**expected repair result**

```json
{
    "b": [
        1,
        [
            {
                "b": 1,
                "c": null
            }
        ]
    ]
}
```

## This is the way I can deal with it now.

```php
$prettyJson = <<<JSON
{
    "b": [
        1,
        [
            {
                "b": 1,
                "c"
JSON;

$json = (new Fixer)->fix($prettyJson);

echo json_encode(json_decode($json, true), JSON_PRETTY_PRINT);
```

**Comment by adhocore** [comment]
thanks. :)
while this is a pretty neat feature, i doubt if we should have it in the library. at the moment this library is meant to only fix the truncated/corrupted json so at least something can be retrieved. to implement this is going to be little complicated as well for no big gain.
at best we can do decode/encode with pretty_print flag as in your example. 
if you can PR for this i would gladly accept.

**Comment by guanguans** [comment]
Thank you for your answer and reply.
