### ISSUE TITLE
Class not found in Drupal

### ISSUE THREAD

**Issue by shahuldatamatics** [adhocore/php-json-fixer#7]
I am using this package in Drupal CMS, installed it into the vendor folder using composer as usual. I tried in every possible way but it throws "Class 'Ahc\Json\Fixer' not found". Please help me to use this library.

**Comment by adhocore** [comment]
please make sure vendor/autoload.php is required or included before.

also please check if there is vendor/adhocore/json-fixer directory.

also if you haven't imported the class with `use`, you can do `\Ahc\Json\Fixer`
